name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Buildozer dependencies
      run: |
        sudo apt install -y git python3 python3-setuptools python3-wheel \
        autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
        libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: bin/*.apk
