name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system tools
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk

    - name: Install Buildozer
      run: |
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer -v android debug
